language: java

jdk:
  - oraclejdk8

#before_install:
#  - wget https://github.com/Anjali05/GSoC2016-Work/tree/master/Framework/target/Framework-0.0.1-SNAPSHOT.jar
env:
  - FRAMEWORK_DIR=Framework
#  - TEST_DIR=Test

addons:
   firefox: "latest"

script:
  - ls
  - cd $FRAMEWORK_DIR && mvn clean && mvn install
  - cd ../Test && mvn compile &&  mvn test
