language: java

jdk:
  - oraclejdk8

#before_install:
#  - wget https://github.com/Anjali05/GSoC2016-Work/tree/master/Framework/target/Framework-0.0.1-SNAPSHOT.jar
env:
  - FRAMEWORK_dir=Framework
  - TEST_DIR=Test

script:
  - ls
  - cd FRAMEWORK_dir && mvn clean && mvn install
  - cd TEST_DIR && mvn install && mvn compile &&  mvn test
